#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

###---Monitors---###
bspc monitor eDP-1 -d 6 7 8 9 10
bspc monitor HDMI-1 -d 1 2 3 4 5

###---Global Settings---###
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 5

bspc config normal_border_color "#000000"
bspc config active_border_color "#000000"
bspc config focused_border_color "#FFFFFF"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

#bspc rule -a Spotify desktop=^5

###---AutoStart---###

$HOME/.config/polybar/launch.sh &
pgrep bspswallow || bspswallow &
#spotify &
